version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: apiZetta
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jhow2006
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d apiZetta"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: api_to_do_list
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/apiZetta
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Jhow2006
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: ${JWT_SECRET_KEY}